title = "gitleaks config"
[[regexes]]
description = "AWS"
regex = '''AKIA[0-9A-Z]{16}'''
[[regexes]]
description = "RKCS8"
regex = '''-----BEGIN PRIVATE KEY-----'''
[[regexes]]
description = "RSA"
regex = '''-----BEGIN RSA PRIVATE KEY-----'''
[[regexes]]
description = "Github"
regex = '''(?i)github.*['\"][0-9a-zA-Z]{35,40}['\"]'''
[[regexes]]
description = "SSH"
regex = '''-----BEGIN OPENSSH PRIVATE KEY-----'''
[[regexes]]
description = "Facebook"
regex = '''(?i)facebook.*['\"][0-9a-f]{32}['\"]'''
[[regexes]]
description = "Twitter"
regex = '''(?i)twitter.*['\"][0-9a-zA-Z]{35,44}['\"]'''
[[regexes]]
description = "PGP"
regex = '''-----BEGIN PGP PRIVATE KEY BLOCK-----'''
[[regexes]]
description = "Slack token"
regex = '''xox[baprs]-.*'''
[[regexes]]
description = "Strip API Key"
regex = '''(?i)(sk|pk)_(test|live)_[0-9a-zA-Z]{10,32}'''
[[regexes]]
description = "Password set with string literal"
regex = '''(?i)[\w]*password[\w]* *[:=] *['"][\S]{8,}['"]'''
[[regexes]]
description = "Password in Rails config"
regex = '''[\w]*password[\w]* *: *[\S]{8,}'''
[[regexes]]
description = "Rails secret key"
regex = '''(?i)(devise_secret_key|secret_key_base)[:= ]+[0-9a-zA-Z]{8,}'''
[[regexes]]
description = "Database connection string"
regex = '''(?i)database_url.*mysql2://'''
[[regexes]]
description = "Alma API key"
regex = '''(?i)alma_api_key.*[0-9a-zA-Z]{36}'''
[[regexes]]
description = "Alma auth secret"
regex = '''(?i)alma_auth_secret.*[0-9a-zA-Z]{8,}'''
[[regexes]]
description = "Summon secret key"
regex = '''(?i)summon_secret_key.*[0-9a-zA-Z]{32}'''

[whitelist]
commits = [
    # Initial commit
    '10b90fd18d590e9db6fef8675aa86a003835b441',
]
files = [
  '\.gitleaks\.toml',
  '(.*?)(jpg|gif|doc|pdf|bin|md)$',
]
